version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - docker --version
      - DOCKER_BUILDKIT=1 docker build -t example-spring-boot-crac .
      - docker run --detach --privileged --rm --name example-spring-boot-crac example-spring-boot-crac /opt/scripts/checkpoint.sh
      - docker exec -u root example-spring-boot-crac /opt/scripts/checkpoint-wait.sh
      - docker commit example-spring-boot-crac example-spring-boot-crac:checkpoint
  post_build:
    commands:
