apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-spring-boot
  template:
    metadata:
      labels:
        app: example-spring-boot
    spec:
      containers:
      - name: example-spring-boot
        image: 536253303170.dkr.ecr.eu-west-2.amazonaws.com/example-spring-boot:5afeb19-checkpoint
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          capabilities:
            add:
              - all
          privileged: true
          runAsUser: 0
          allowPrivilegeEscalation: true
        command: ["/bin/bash"]
        args: ["/opt/scripts/run-service.sh"]

